import { Random } from "meteor/random";
export default {
  generate: (leader) => {
    return {
      name: leader.name,
      designation: leader.designation,
      country: leader.country,
      flag: leader.flag,
      image: leader.image,
      slots: [
        { _id: Random.id(), label: "00:00", intercessors: 0 },
        { _id: Random.id(), label: "00:15", intercessors: 0 },
        { _id: Random.id(), label: "00:30", intercessors: 0 },
        { _id: Random.id(), label: "00:45", intercessors: 0 },
        { _id: Random.id(), label: "01:00", intercessors: 0 },
        { _id: Random.id(), label: "01:15", intercessors: 0 },
        { _id: Random.id(), label: "01:30", intercessors: 0 },
        { _id: Random.id(), label: "01:45", intercessors: 0 },
        { _id: Random.id(), label: "02:00", intercessors: 0 },
        { _id: Random.id(), label: "02:15", intercessors: 0 },
        { _id: Random.id(), label: "02:30", intercessors: 0 },
        { _id: Random.id(), label: "02:45", intercessors: 0 },
        { _id: Random.id(), label: "03:00", intercessors: 0 },
        { _id: Random.id(), label: "03:15", intercessors: 0 },
        { _id: Random.id(), label: "03:30", intercessors: 0 },
        { _id: Random.id(), label: "03:45", intercessors: 0 },
        { _id: Random.id(), label: "04:00", intercessors: 0 },
        { _id: Random.id(), label: "04:15", intercessors: 0 },
        { _id: Random.id(), label: "04:30", intercessors: 0 },
        { _id: Random.id(), label: "04:45", intercessors: 0 },
        { _id: Random.id(), label: "05:00", intercessors: 0 },
        { _id: Random.id(), label: "05:15", intercessors: 0 },
        { _id: Random.id(), label: "05:30", intercessors: 0 },
        { _id: Random.id(), label: "05:45", intercessors: 0 },
        { _id: Random.id(), label: "06:00", intercessors: 0 },
        { _id: Random.id(), label: "06:15", intercessors: 0 },
        { _id: Random.id(), label: "06:30", intercessors: 0 },
        { _id: Random.id(), label: "06:45", intercessors: 0 },
        { _id: Random.id(), label: "07:00", intercessors: 0 },
        { _id: Random.id(), label: "07:15", intercessors: 0 },
        { _id: Random.id(), label: "07:30", intercessors: 0 },
        { _id: Random.id(), label: "07:45", intercessors: 0 },
        { _id: Random.id(), label: "08:00", intercessors: 0 },
        { _id: Random.id(), label: "08:15", intercessors: 0 },
        { _id: Random.id(), label: "08:30", intercessors: 0 },
        { _id: Random.id(), label: "08:45", intercessors: 0 },
        { _id: Random.id(), label: "09:00", intercessors: 0 },
        { _id: Random.id(), label: "09:15", intercessors: 0 },
        { _id: Random.id(), label: "09:30", intercessors: 0 },
        { _id: Random.id(), label: "09:45", intercessors: 0 },
        { _id: Random.id(), label: "10:00", intercessors: 0 },
        { _id: Random.id(), label: "10:15", intercessors: 0 },
        { _id: Random.id(), label: "10:30", intercessors: 0 },
        { _id: Random.id(), label: "10:45", intercessors: 0 },
        { _id: Random.id(), label: "11:00", intercessors: 0 },
        { _id: Random.id(), label: "11:15", intercessors: 0 },
        { _id: Random.id(), label: "11:30", intercessors: 0 },
        { _id: Random.id(), label: "11:45", intercessors: 0 },
        { _id: Random.id(), label: "12:00", intercessors: 0 },
        { _id: Random.id(), label: "12:15", intercessors: 0 },
        { _id: Random.id(), label: "12:30", intercessors: 0 },
        { _id: Random.id(), label: "12:45", intercessors: 0 },
        { _id: Random.id(), label: "13:00", intercessors: 0 },
        { _id: Random.id(), label: "13:15", intercessors: 0 },
        { _id: Random.id(), label: "13:30", intercessors: 0 },
        { _id: Random.id(), label: "13:45", intercessors: 0 },
        { _id: Random.id(), label: "14:00", intercessors: 0 },
        { _id: Random.id(), label: "14:15", intercessors: 0 },
        { _id: Random.id(), label: "14:30", intercessors: 0 },
        { _id: Random.id(), label: "14:45", intercessors: 0 },
        { _id: Random.id(), label: "15:00", intercessors: 0 },
        { _id: Random.id(), label: "15:15", intercessors: 0 },
        { _id: Random.id(), label: "15:30", intercessors: 0 },
        { _id: Random.id(), label: "15:45", intercessors: 0 },
        { _id: Random.id(), label: "16:00", intercessors: 0 },
        { _id: Random.id(), label: "16:15", intercessors: 0 },
        { _id: Random.id(), label: "16:30", intercessors: 0 },
        { _id: Random.id(), label: "16:45", intercessors: 0 },
        { _id: Random.id(), label: "17:00", intercessors: 0 },
        { _id: Random.id(), label: "17:15", intercessors: 0 },
        { _id: Random.id(), label: "17:30", intercessors: 0 },
        { _id: Random.id(), label: "17:45", intercessors: 0 },
        { _id: Random.id(), label: "18:00", intercessors: 0 },
        { _id: Random.id(), label: "18:15", intercessors: 0 },
        { _id: Random.id(), label: "18:30", intercessors: 0 },
        { _id: Random.id(), label: "18:45", intercessors: 0 },
        { _id: Random.id(), label: "19:00", intercessors: 0 },
        { _id: Random.id(), label: "19:15", intercessors: 0 },
        { _id: Random.id(), label: "19:30", intercessors: 0 },
        { _id: Random.id(), label: "19:45", intercessors: 0 },
        { _id: Random.id(), label: "20:00", intercessors: 0 },
        { _id: Random.id(), label: "20:15", intercessors: 0 },
        { _id: Random.id(), label: "20:30", intercessors: 0 },
        { _id: Random.id(), label: "20:45", intercessors: 0 },
        { _id: Random.id(), label: "21:00", intercessors: 0 },
        { _id: Random.id(), label: "21:15", intercessors: 0 },
        { _id: Random.id(), label: "21:30", intercessors: 0 },
        { _id: Random.id(), label: "21:45", intercessors: 0 },
        { _id: Random.id(), label: "22:00", intercessors: 0 },
        { _id: Random.id(), label: "22:15", intercessors: 0 },
        { _id: Random.id(), label: "22:30", intercessors: 0 },
        { _id: Random.id(), label: "22:45", intercessors: 0 },
        { _id: Random.id(), label: "23:00", intercessors: 0 },
        { _id: Random.id(), label: "23:15", intercessors: 0 },
        { _id: Random.id(), label: "23:30", intercessors: 0 },
        { _id: Random.id(), label: "23:45", intercessors: 0 },
      ],
    };
  },
};
